### ISSUE TITLE
apply rusftmt on codebase and gate CI on formatting

### ISSUE THREAD

**Issue by rukai** [shotover/rust-cql3-parser#16]
Would be best to do this once the open PR lands

**Comment by conorbros** [comment]
This is already setup. Check the `.workflows`.

**Comment by rukai** [comment]
Oh I see, only one file is unformatted.
there must be something wrong with the CI

**Comment by rukai** [comment]
Oh I figured it out, im operating off claudes repo instead of the shotover one.
sorry for the trouble.
