### ISSUE TITLE
Remove all instances of Option<Vec<T>>

### ISSUE THREAD

**Issue by rukai** [shotover/rust-cql3-parser#2]
Unless None has a unique semantic meaning instead of just vec!() then all instances of Option<Vec<T>> should be replaced with just Vec<T>
![image](https://user-images.githubusercontent.com/5120858/159402152-961fd203-9145-411b-8a49-b562c87fd24d.png)

**Comment by Claude-at-Instaclustr** [comment]
These are removed in the modularization branch.  This issue can  be closed when that branch is merged.

**Comment by Claude-at-Instaclustr** [comment]
Resolved during merge of modularization branch
