### ISSUE TITLE
CassandraAST::new needs to return Result<CassandraAst> Instead of CassandraAST

### ISSUE THREAD

**Issue by rukai** [shotover/rust-cql3-parser#5]
Currently it panics internally when it fails to parse but we need to be able to handle this failure in shotover instead of panicking.

**Comment by Claude-at-Instaclustr** [comment]
Do you ahve a test case for this.

**Comment by rukai** [comment]
A test can not be written yet as the API does not yet allow for error handling.

This needs to return a Result
https://github.com/Claude-at-Instaclustr/rust_cql3_parser/blob/93d12d0e488608de802bc3701bbc57414593d4dd/src/cassandra_ast.rs#L1967

This needs to bubble up the Err case instead of unwrap.
https://github.com/Claude-at-Instaclustr/rust_cql3_parser/blob/93d12d0e488608de802bc3701bbc57414593d4dd/src/cassandra_ast.rs#L1981

**Comment by Claude-at-Instaclustr** [comment]
The parser makes a  best effort parse.  So even in the case of an error it
should return a result and a flag indicating there is an error in the
parse.  Cna you give me an example of a statement that panics?

**Comment by Claude-at-Instaclustr** [comment]
I have added a test case in cassandra_statements.rs

```
fn test_invalid_statement() {
        let stmt = "This is an invalid statement";
        let ast = CassandraAST::new(stmt.to_string());
        assert!(ast.has_error() );
        let stmt = &ast.statement;
        assert!( match ast.statement {
            CassandraStatement::Unknown(_) => true,
            _ => false,
        });
        let stmt_str = stmt.to_string();
        assert_eq!(stmt.to_string(), stmt_str);
        assert_eq!( stmt.to_string(), match ast.statement {
            CassandraStatement::Unknown(text) => text,
            _ => "".to_string(),
        });
    }
```


This shows that an invalid statement does not panic and that a result returned as the statement and as the text in the CassandraStatement::Unknown is the input string.

**Comment by rukai** [comment]
Oh I see!
I missed that the error case was being handled as a `CassandraStatement::Unknown`.

In shotover we could just directly replace the CQL struct with CassandraStatement.
https://github.com/shotover/shotover-proxy/blob/d5f90a7d6ef6c414eec6bf931b505ce8bf18ec11/shotover-proxy/src/frame/cassandra.rs#L466
